<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
data = pd.read_csv('/datasets/insurance.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [3]:
data.sample(10)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
94      0     32.0   33300.0            0                  0
3859    0     22.0   46800.0            2                  0
352     0     31.0   32900.0            1                  0
3511    1     26.0   51100.0            1                  0
3405    1     22.0   45000.0            4                  0
3251    0     49.0   25900.0            1                  2
3933    1     27.0   30000.0            1                  0
976     1     30.0   37000.0            3                  0
3170    0     36.0   54000.0            3                  0
1145    1     21.0   50600.0            2                  0

In [4]:
#замена типа данных в столбцах Возраст и Зарплата на целочисленный, т.к.в записях этих столбцов отсуствуют дробные части
data['Возраст'] = data['Возраст'].astype('int')
data['Зарплата'] = data['Зарплата'].astype('int')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null int64
Зарплата             5000 non-null int64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: int64(5)
memory usage: 195.4 KB


**Вывод**

Данные загружены и изучены, не имеют пропущенных значений, различного рода аномалий не наблюдается, выполнено изменение типов.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)
 - a. Изменится. Приведите примеры матриц.
 - b. Не изменится. Укажите, как связаны параметры линейной регрессии в исходной задаче и в преобразованной.

**Ответ:** 

Не изменится

**Обоснование:** 

Заменим матрицу $X$ на матрицу $Z$:

$$
Z = XP \qquad (2.1)
$$
где $P$ - обратимая матрица с некими значениями, на которую может быть умножена матрица $X$.


Заменим $X$ на $Z$ и вычислим, чему будет равено предсказание и вектор весов.

$$
a_1 = Zw_1 \qquad (2.2)
$$$$
w_1 = (Z^T Z)^{-1} Z^T y \qquad (2.3)
$$
Подставим уравнение 2.2 правую часть уравнения 2.3 и получим следущее:

$$
a_1 = Z (Z^T Z)^{-1} Z^T y \qquad (2.4)
$$
Заменим все $Z$ правой частью уравнения 2.1:

$$
a_1 = XP ((XP)^T (XP))^{-1} (XP)^T y \qquad (2.5)
$$
Для следующего шага понадобится следующее свойсво обратной матрицы:

$$
(AB)^{-1} = B^{-1} A^{-1}
$$
Раскроем $((XP)^T (XP))^{-1}$ в два шага:

$$
a_1 = XP ((XP)^T (XP))^{-1} (XP)^T y = XP(XP)^{-1}((XP)^T)^{-1} (XP)^T y = XPP^{-1}X^{-1}((XP)^T)^{-1} (XP)^T y  \qquad (2.6)
$$
Умножение приведет к $PP^{-1} = E$. Для следуюзего этапа воспользуемся свойством транспорнированной матрицы:

$$
(AB)^T = B^T A^T
$$
Умножение на единичную матрицу ничего не меняет. Раскроем $((XP)^T)^{-1} (XP)^T$ в три шага:

$$
a_1 = XEX^{-1}((XP)^T)^{-1} (XP)^T y = XX^{-1}(P^T X^T)^{-1} P^T X^T y = XX^{-1} (X^T)^{-1} (P^T)^{-1}  P^T X^T y   \qquad (2.7)
$$
Умножение приведет к $(P^T)^{-1}  P^T = E$. Посмотрим, что осталось от уравнения 2.7:

$$
a_1 = XX^{-1} (X^T)^{-1} E X^T y = X(X^T X)^{-1} X^T y = Xw = a  \qquad (2.8)
$$
Как видно, значение предсказания $a$ не меняется, если умножать матрицу признаков на обратимую матрицу.

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$
При подстановке в формулы вместо X - XP, получаем:

Предсказания:

$$
a = XPw
$$
Формула обучения:

$$
w = ((XP)^T XP)^{-1} (XP)^T y
$$
Тогда формула предсказания:$$
a = XP((XP)^T XP)^{-1} (XP)^T y
$$

При раскрытии скобок для транспонируемых матриц меняется порядок умножения:

$$
a = XP(P^T X^T XP)^{-1} P^T X^T y
$$
Далее раскрываем скобки для инверсии, порядок снова меняется:

$$
a = XP(P)^{-1}(P^T X^T X)^{-1} P^T X^T y
$$$$
a = XP(P)^{-1}(X^T X)^{-1} P^{T^{-1}} P^T X^T y
$$
Произведение матрицы на обратную даёт единичную матрицу:

$$
a = XE(X^T X)^{-1} E X^T y
$$
И умножение на единичную матрицу оставляет исходную матрицу, получаем:

$$
a = X(X^T X)^{-1} X^T y
$$
что эквивалентно формуле предсказаний, для исходного набора признаков:

$$
a = Xw
$$

## Алгоритм преобразования

**Алгоритм**

1. Составление матрицы $Y$.
2. Проверка матрицы на обратимость. Вычисление детерминанта матрицы $Y$.
3. Получение матрицы преобразованных признаков $Z = XY$.
4. Применение алгоритма на преобразованных признаках $Z$.

**Обоснование**

Матрица $Y$ должна иметь необходимую размерность $(nxn)$, где n - количество признаков для регрессии. Таким образом матрица $Z$ будет иметь туже размерность, что и матрица $X$. Обратная матрица $Y$ существует только для квадратных невырожденных матриц (определитель которых не равен нулю).

Пример:

$
X = \begin{pmatrix}
1 &amp; 2 \\
2 &amp; 3 \\
4 &amp; 5  
\end{pmatrix}
\qquad 
Y = \begin{pmatrix}
1 &amp; 0 \\
2 &amp; 3 \\  
\end{pmatrix}
\qquad det  Y = 3 $

Найдем значние Z:

$
Z = \begin{pmatrix}
1 &amp; 2 \\
2 &amp; 3 \\
4 &amp; 5  
\end{pmatrix} \begin{pmatrix}
1 &amp; 0 \\
2 &amp; 3 \\  
\end{pmatrix} = \begin{pmatrix}
1*1+2*2 &amp; 1*0+2*3  \\
2*1+3*2 &amp; 2*0+3*3  \\
4*1+5*2 &amp; 4*0+5*3   
\end{pmatrix} = \begin{pmatrix}
5 &amp; 6 \\
8 &amp; 9 \\
14 &amp; 15  
\end{pmatrix}$

После этого добавляем нулевой столбец и вводим данные в линейную регрессию.

In [7]:
X = np.concatenate((np.ones((features.shape[0], 1)), features), axis=1)
y = target
w = np.linalg.inv(X.T @ X) @ X.T @ y
display(w[1:])
model = LinearRegression()
model.fit(features, target)
model.coef_

array([ 7.92580563e-03,  3.57083050e-02, -1.70081903e-07, -1.35676627e-02])

array([ 7.92580563e-03,  3.57083050e-02, -1.70081903e-07, -1.35676627e-02])

Проведем исследование модели без преобразования и с преобразованием.

In [9]:
#разбиение данные на обучающие и тестовые выборки
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.25, random_state=7072020)

In [11]:
#без преобразования признаков
model = LinearRegression()
model.fit(features_train, target_train)
R2_LR_origin_data = r2_score(target_test, model.predict(features_test))
print("R2 =", R2_LR_origin_data)

R2 = 0.4184108158256682


In [17]:
#преобразование признаков
def cipher_features(features):
    crypted_features = features
    n = features.shape[1]
    np.random.seed(7072020)
    cipher_matrix = np.random.randint(1, 10, (n,n))
    det = np.linalg.det(cipher_matrix)
    while det == 0:
        np.random.seed(7072021)
        cipher_matrix = np.random.randint(1, 10, (n,n))
        det = np.linalg.det(cipher_matrix)
    crypted_features = crypted_features.dot(cipher_matrix)
    return crypted_features, cipher_matrix

In [18]:
display(features.head())
features, cipher_matrix = cipher_features(features)
display(features.head())
cipher_matrix

0      1      2       3
0  397184  49981  99373  248097
1  304422  38421  76185  190101
2  168261  21261  42116  105058
3  333805  41903  83486  208560
4  209059  26357  52320  130562

0        1        2        3
0  6009877  4271801  3824239  5212804
1  4607031  3274791  2931531  3995208
2  2546568  1810176  1620422  2208190
3  5050130  3589558  3213584  4381106
4  3163682  2248762  2013102  2743726

array([[7, 5, 8, 6],
       [9, 9, 4, 2],
       [8, 1, 2, 5],
       [8, 7, 1, 9]])

In [19]:
#разбиение данных на обучающую и тестовую выборки и проверка R2-значения
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.25, random_state=7072020)

In [20]:
#с преобразованием признаков
model = LinearRegression()
model.fit(features_train, target_train)
R2_LR_cipher_data = r2_score(target_test, model.predict(features_test))
print("R2 =", R2_LR_cipher_data)

R2 = 0.41841081582575934


**Вывод**

Применив метрику R2, проверка показала, что качество линейной регрессии не отличается до и после преобразования.